http:
  listener:
    host: "0.0.0.0"
    port: "8083"
   
  requester:
    host: "0.0.0.0"
    port: "8081"
    routesPath: "/travelOnTip/routes"
    schedulesPath: "/travelOnTip/schedules"
    
    